"""made both columns in user_booking primary key

Revision ID: 22459b955ea9
Revises: 3820bb1d0000
Create Date: 2026-08-07 13:05:53.939893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22459b955ea9'
down_revision = '3820bb1d0000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_booking', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_booking', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
