"""initial schema

Revision ID: 3820bb1d0000
Revises: 
Create Date: 2026-08-06 13:46:34.136322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3820bb1d0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('staff_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('Address', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('available_slots', sa.Integer(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trek_id', sa.Integer(), nullable=True),
    sa.Column('booking_status', sa.String(length=200), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('payment_status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['trek_id'], ['trek.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_booking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_booking')
    op.drop_table('booking')
    op.drop_table('user_roles')
    op.drop_table('trek')
    op.drop_table('staff_profile')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
