"""add name to trek

Revision ID: 50e8ea303060
Revises: a61b148cbfc2
Create Date: 2026-07-30 11:47:13.896468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e8ea303060'
down_revision = 'a61b148cbfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trek', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
