"""Add assigned_staff_id to trek

Revision ID: dffcfbdb413d
Revises: 50e8ea303060
Create Date: 2026-08-03 21:06:07.615578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffcfbdb413d'
down_revision = '50e8ea303060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trek', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_staff_id')

    # ### end Alembic commands ###
